/auth/register:
  post:
    tags:
      - "auth"
    summary: "Register user"
    description: "Register user"
    operationId: "register"
    consumes:
      - "application/x-www-form-urlencoded"
    produces:
      - "application/json"
    parameters:
      - name: "username"
        in: "formData"
        description: "username for new user"
        required: true
        type: "string"
      - name: "email"
        in: "formData"
        description: "email for new user"
        required: true
        type: "email"
      - name: "password"
        in: "formData"
        description: "password for new user"
        required: true
        type: "string"
    responses:
      200:
        description: "successful operation"

/auth/login:
  post:
    tags:
      - "auth"
    summary: "Login to get jwt"
    description: ""
    operationId: "login"
    consumes:
      - "application/x-www-form-urlencoded"
    produces:
      - "application/json"
    parameters:
      - name: "email"
        in: "formData"
        description: "email user"
        required: true
        type: "string"
      - name: "password"
        in: "formData"
        description: "password user"
        required: true
        type: "string"
    responses:
      200:
        description: "successful operation"

/auth/check-email-username:
  post:
    tags:
      - "auth"
    summary: "check email and username"
    description: ""
    operationId: "checkEmailUsername"
    consumes:
      - "application/x-www-form-urlencoded"
    produces:
      - "application/json"
    parameters:
      - name: "type"
        in: "formData"
        description: "type of data to check"
        required: true
        type: "array"
        items:
          type: "string"
          enum:
            - "email"
            - "username"
          default: "email"
      - name: "data"
        in: "formData"
        description: "data to check"
        required: true
        type: "string"
    responses:
      200:
        description: "successful operation"
